# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20170408_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('block', models.CharField(max_length=20, verbose_name='Building name')),
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Room number')),
                ('floor_number', models.PositiveIntegerField(verbose_name='Floor number')),
                ('maximum_capacity', models.PositiveIntegerField(verbose_name='Maximum room size')),
                ('projector', models.CharField(max_length=20, verbose_name='Projector condition')),
                ('computer', models.CharField(max_length=20, verbose_name='Computer condition')),
                ('air_conditioner', models.CharField(max_length=20, verbose_name='AC condition')),
                ('speakers', models.CharField(max_length=20, verbose_name='Speakes condition')),
            ],
        ),
        migrations.CreateModel(
            name='labs',
            fields=[
                ('block', models.CharField(max_length=20, verbose_name='Building name')),
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Room number')),
                ('floor_number', models.CharField(max_length=10, verbose_name='Floor number')),
                ('maximum_capacity', models.CharField(max_length=5, verbose_name='Maximum room size')),
                ('type', models.CharField(max_length=20, verbose_name='Type of Lab')),
                ('air_conditioner', models.CharField(max_length=20, verbose_name='AC condition')),
            ],
        ),
        migrations.CreateModel(
            name='requestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(verbose_name='time stamp')),
                ('block', models.CharField(max_length=20, verbose_name='Building name')),
                ('room_number', models.CharField(max_length=10, verbose_name='Room number')),
                ('block_type', models.CharField(choices=[('classroom', 'CLASSROOM'), ('lab', 'LAB')], default='classroom', max_length=10, verbose_name='Block type')),
                ('startDateTime', models.CharField(max_length=30, verbose_name='startDateTime')),
                ('endDateTime', models.CharField(max_length=30, verbose_name='endDateTime')),
                ('sender', models.CharField(max_length=10, verbose_name='sender')),
                ('granter', models.CharField(max_length=10, verbose_name='granter')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('booking_status', models.CharField(default=0, max_length=1, verbose_name='booking status')),
            ],
        ),
    ]
