# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_classroom_labs_requesttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='block',
            field=models.CharField(choices=[('cc1', 'COMPUTER CENTER- 1'), ('cc2', 'COMPUTER CENTER- 2'), ('cc3', 'COMPUTER CENTER- 3'), ('lt', 'LECTURE THEATRE')], max_length=20, verbose_name='Building name'),
        ),
    ]
