# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-08 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_auto_20170408_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='block',
            field=models.CharField(choices=[('cc1', 'COMPUTER CENTER- 1'), ('cc2', 'COMPUTER CENTER- 2'), ('cc3', 'COMPUTER CENTER- 3'), ('lt', 'LECTURE THEATRE')], max_length=20, verbose_name='Building name'),
        ),
        migrations.AlterField(
            model_name='labs',
            name='type',
            field=models.CharField(choices=[('computer', 'COMPUTER'), ('physics', 'PHYSICS'), ('vlsi', 'VLSI')], max_length=20, verbose_name='Type of Lab'),
        ),
    ]
